#!/bin/sh

VOL=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")
VOLMUTE=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)\].*/\1/")
printf "%s" "$SEP1"
if [ "$VOLMUTE" = "off" ]; then
    printf "󰝟 %s%%" "$VOL"
elif [ "$VOL" -eq 0 ]; then
    printf "󰕿"
elif [ "$VOL" -gt 0 ] && [ "$VOL" -le 33 ]; then
    printf "󰖀 %s%%" "$VOL"
elif [ "$VOL" -gt 33 ] && [ "$VOL" -le 66 ]; then
    printf "󰕾 %s%%" "$VOL"
else
    printf "󱄡 %s%%" "$VOL"
fi
printf "%s\n" "$SEP2"

