#!/bin/sh

# Change BAT1 to whatever your battery is identified as. Typically BAT0 or BAT1
CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
# full Not charging Discharging
printf "%s" "$SEP1"
if [ "$IDENTIFIER" = "unicode" ]; then
    if [ "$STATUS" = "Not charging" ]; then
        printf "🔌 %s%% %s" "$CAPACITY" #"$STATUS"
    else
        printf "🔋 %s%% %s" "$CAPACITY" #"$STATUS"
    fi
else
    if [ "$STATUS" = "Discharging" ]; then
        if [ "$CAPACITY" -eq 100 ]; then
            printf "󰁹 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 90 ] && [ "$CAPACITY" -le 100 ]; then
            printf "󰂂 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 80 ] && [ "$CAPACITY" -le 90 ]; then
            printf "󰂁 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 70 ] && [ "$CAPACITY" -le 80 ]; then
            printf "󰂀 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 60 ] && [ "$CAPACITY" -le 70 ]; then
            printf "󰁿 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 50 ] && [ "$CAPACITY" -le 60 ]; then
            printf "󰁾 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 40 ] && [ "$CAPACITY" -le 50 ]; then
            printf "󰁽 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 30 ] && [ "$CAPACITY" -le 40 ]; then
            printf "󰁼 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 20 ] && [ "$CAPACITY" -le 30 ]; then
            printf "󰁻 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 10 ] && [ "$CAPACITY" -le 20 ]; then
            printf "󰁺 %s%%" "$CAPACITY" #"$STATUS"
        else
            printf "󱉞 %s%%" "$CAPACITY" #"$STATUS"
            notify-send "没电了，赶紧充电啊！！！"
        fi
    elif [ "$STATUS" = "Not charging" ]; then
        printf " %s%%" "$CAPACITY" #"$STATUS"
    elif [ "$STATUS" = "Charging" ]; then
        if [ "$CAPACITY" -le 10 ]; then
            printf "󰢟 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 10 ] && [ "$CAPACITY" -le 20 ]; then
            printf "󰢜 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 20 ] && [ "$CAPACITY" -le 30 ]; then
            printf "󰂆 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 30 ] && [ "$CAPACITY" -le 40 ]; then
            printf "󰂇 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 40 ] && [ "$CAPACITY" -le 50 ]; then
            printf "󰂈 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 50 ] && [ "$CAPACITY" -le 60 ]; then
            printf "󰢝 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 60 ] && [ "$CAPACITY" -le 70 ]; then
            printf "󰂉 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 70 ] && [ "$CAPACITY" -le 80 ]; then
            printf "󰢞 %s%%" "$CAPACITY" #"$STATUS"
        elif [ "$CAPACITY" -gt 80 ] && [ "$CAPACITY" -le 90 ]; then
            printf "󰂊 %s%%" "$CAPACITY" #"$STATUS"
        else
            printf "󰂋 %s%%" "$CAPACITY" #"$STATUS"
        fi
    else
        printf "󰂅 %s%%" "$CAPACITY" #"$STATUS"
    fi
fi
printf "%s\n" "$SEP2"
