#!/bin/sh

mem_total=$(cat /proc/meminfo | grep "MemTotal:"| awk '{print $2}')
mem_free=$(cat /proc/meminfo | grep "MemFree:"| awk '{print $2}')
mem_buffers=$(cat /proc/meminfo | grep "Buffers:"| awk '{print $2}')
mem_cached=$(cat /proc/meminfo | grep -w "Cached:"| awk '{print $2}')
men_usage_rate=$(((mem_total - mem_free - mem_buffers - mem_cached) * 100 / mem_total))
mem_text=$(echo $men_usage_rate | awk '{printf "%d%", $1}')
echo -e "󰍛 $mem_text"
