#!/bin/sh

printf "%s" "$SEP1"
if [ "$IDENTIFIER" = "unicode" ]; then
    printf "🥮 %s" "$(lunar-date | awk -F '年' 'NR == 2 {print $2}')"
else
    printf "%s" "$(lunar-date | awk -F '年' 'NR == 2 {print $2}')"
fi
printf "%s\n" "$SEP2"
