#!/bin/sh

CONNAME=$(nmcli -a | grep 'wlp0s20f3' | awk 'NR==1{print $3}')
if [ "$CONNAME" = "" ]; then
    CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)
fi
PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}')
PUBLIC=$(curl -u bd76e54350f0ef: ipinfo.io | grep '"ip' | awk -F '\"' '{print $4}')
CITY=$(curl -u bd76e54350f0ef: ipinfo.io | grep '"city' | awk -F '\"' '{print $4}')
printf "%s" "$SEP1"
if [ "$IDENTIFIER" = "unicode" ]; then
    printf "🌐 %s %s | %s" "$CONNAME" "$PRIVATE" "$PUBLIC"
else
    printf "󰩟 %s|%s" "$PUBLIC" "$CITY"
fi
printf "%s\n" "$SEP2"
