#!/bin/sh
# Utility functions for theming statusbar scripts.

display() {
    if [ -n "$2" ]; then
        color="$2"
    else
        case "$(basename "$0")" in
            dwm_memory) color=13 ;;
            dwm_cpu) color=14 ;;
            dwm_disk) color=10 ;;
            dwm_network) color=15 ;;
            dwm_volume) color=11 ;;
            dwm_battery) color=9 ;;
            dwm_date) color=9 ;;
            dwm_lunar) color=15 ;;
            sb-battery) color=14 ;;
            sb-date) color=12 ;;
            sb-network) color=9 ;;
            *) color=15 ;;
        esac
    fi

    case "$STATUSBAR" in
        "dwmblocks")
            echo "^C$color^$1"
            ;;
        *)
            echo "$1"
            ;;
    esac
}
